In [2]:
import statsmodels.api as sm
import numpy as np
from statsmodels.stats.contingency_tables import StratifiedTable

import pandas

In [3]:
df = pandas.read_csv('dat/RESULTS.csv')
df[:3]

set drug method         dataset quality  sensitivity  sensitivity_sem  \
0  basic  INH  UKMYC  bootstrapped50     ALL    91.240875         0.480167   
1  basic  INH  UKMYC  bootstrapped50    HIGH    93.746796         0.336085   
2  basic  INH  UKMYC          entire     ALL    91.200000         0.000000   

   specificity  specificity_sem        PPV   PPV_sem     RR    SR    UR    RS  \
0    95.395150         0.367757  95.206597  0.370676    NaN   NaN   NaN   NaN   
1    96.624866         0.352979  96.618858  0.342746    NaN   NaN   NaN   NaN   
2    95.600000         0.000000  95.397490  0.000000  456.0  33.0  11.0  22.0   

      SS    US   Total  
0    NaN   NaN     NaN  
1    NaN   NaN     NaN  
2  448.0  30.0  1000.0

In [24]:
df[(df.drug=='AMI') & (df.dataset=='entire') & (df.set=='basic')]

set drug method dataset quality  sensitivity  sensitivity_sem  \
38  basic  AMI  UKMYC  entire     ALL    71.180556              0.0   
39  basic  AMI  UKMYC  entire    HIGH    80.816327              0.0   

    specificity  specificity_sem        PPV  PPV_sem     RR    SR   UR   RS  \
38    99.578652              0.0  98.557692      0.0  205.0  76.0  7.0  3.0   
39    99.482759              0.0  98.507463      0.0  198.0  43.0  4.0  3.0   

       SS    US   Total  
38  656.0  53.0  1000.0  
39  540.0  37.0   825.0

In [13]:
drug='AMI'
tables = []
for quality in ['ALL', 'HIGH']:
    row = df[(df.set=='basic') & (df.drug==drug) & (df.dataset=='entire') & (df.quality==quality)]
    tab = np.array([[int(row.RR), int(row.RS)],],) # [int(row.SR+row.UR), int(row.SS+row.US)]])
    # tab = np.array([ [int(row.SS+row.US), int(row.SR+row.UR), ], [int(row.RS), int(row.RR),], ])
    tables.append(tab)
tables

/var/folders/84/9nb2gsqj4hlcxztvwf19wg680000gq/T/ipykernel_43157/2796810178.py:5: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  tab = np.array([[int(row.RR), int(row.RS)],],) # [int(row.SR+row.UR), int(row.SS+row.US)]])


[array([[205,   3]]), array([[198,   3]])]

In [15]:
st = sm.stats.StratifiedTable([tables])

print(st.summary())

ValueError: If `tables` is a list, all of its elements should be 2x2

In [12]:
st.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [9]:
drug, st.summary()
a=st.summary()
a.data

[['', 'Estimate', 'LCB', 'UCB'],
 ['Pooled odds', '0.811', '0.459', '1.434'],
 ['Pooled log odds', '-0.209', '-0.779', '0.361'],
 ['Pooled risk ratio', '0.989', '', ''],
 ['', '', '', ''],
 ['', 'Statistic', 'P-value', ''],
 ['Test of OR=1', '0.518', '0.472', ''],
 ['Test constant OR', '0.000', 'nan', ''],
 ['', '', '', ''],
 ['Number of tables', '1', '', ''],
 ['Min n', '916', '', ''],
 ['Max n', '916', '', ''],
 ['Avg n', '916', '', ''],
 ['Total n', '916', '', '', '']]

In [25]:
tables = []

for drug in ['AMI', 'CFZ', 'DLM', 'EMB', 'ETH', 'INH', 'KAN', 'LEV', 'LZD', 'MXF', 'RIF']:

# for drug in ['AMI', 'CFZ', 'DLM', 'EMB', 'ETH', 'INH', 'KAN', 'LEV', 'LZD', 'MXF', 'RIF']:
# ['RIF', 'INH', 'EMB', 'KAN', 'AMI', 'CFZ', 'DLM', 'ETH', 'LEV', 'MXF', 'LZD']:
    tab = []
    for quality in ['ALL', 'HIGH']:
        row = df[(df.set=='basic') & (df.drug==drug) & (df.dataset=='entire') & (df.quality==quality)]
        # tab = np.array([[int(row.RR), int(row.RS)], [int(row.SR+row.UR), int(row.SS+row.US)]])
        tab.append([int(row.RR), int(row.SR+row.UR), ],)
    st = sm.stats.StratifiedTable([tab])
    a=st.summary().data
    for i in a:
        if i[0]=='Test of OR=1':
            print(drug, i[2])
    # print(drug,tab, st.summary())
    tables.append(tab)
tables

AMI 0.010
CFZ 0.566
DLM 0.116
EMB 0.386
ETH 0.220
INH 0.111
KAN 0.028
LEV 0.298
LZD 0.067
MXF 0.312
RIF 0.472


/var/folders/84/9nb2gsqj4hlcxztvwf19wg680000gq/T/ipykernel_43157/704452060.py:11: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  tab.append([int(row.RR), int(row.SR+row.UR), ],)


[[[205, 83], [198, 47]],
 [[20, 268], [4, 74]],
 [[17, 123], [13, 50]],
 [[245, 43], [200, 28]],
 [[203, 85], [191, 63]],
 [[456, 44], [432, 28]],
 [[213, 76], [212, 48]],
 [[251, 72], [212, 49]],
 [[26, 91], [22, 41]],
 [[234, 54], [198, 36]],
 [[447, 29], [418, 22]]]

In [21]:
print(st.summary())

                   Estimate   LCB    UCB  
------------------------------------------
Pooled odds           0.586   0.390  0.881
Pooled log odds      -0.534  -0.942 -0.126
Pooled risk ratio     0.881               
                                          
                 Statistic P-value 
-----------------------------------
Test of OR=1         6.653   0.010 
Test constant OR     0.000     nan 
                      
----------------------
Number of tables   1  
Min n            533  
Max n            533  
Avg n            533  
Total n          533  
----------------------


In [5]:
tables

[[[502, 22], [425, 15]],
 [[478, 22], [430, 16]],
 [[607, 105], [444, 95]],
 [[704, 7], [613, 7]],
 [[709, 3], [577, 3]],
 [[698, 14], [586, 12]],
 [[859, 1], [686, 0]],
 [[623, 89], [528, 81]],
 [[656, 21], [513, 16]],
 [[674, 38], [468, 30]],
 [[882, 1], [656, 0]]]

In [6]:
tables[0]

[[502, 22], [425, 15]]

                   Estimate   LCB     UCB  
-------------------------------------------
Pooled odds         289.235 193.142 433.138
Pooled log odds       5.667   5.263   6.071
Pooled risk ratio    22.538                
                                           
                 Statistic P-value 
-----------------------------------
Test of OR=1      1491.873   0.000 
Test constant OR     2.133   0.144 
                       
-----------------------
Number of tables    2  
Min n             906  
Max n            1000  
Avg n             953  
Total n          1906  
-----------------------


                   Estimate   LCB    UCB 
-----------------------------------------
Pooled odds           1.237   0.913 1.675
Pooled log odds       0.213  -0.091 0.516
Pooled risk ratio     1.035              
                                         
                 Statistic P-value 
-----------------------------------
Test of OR=1         1.890   0.169 
Test constant OR     0.000     nan 
                       
-----------------------
Number of tables    1  
Min n            1251  
Max n            1251  
Avg n            1251  
Total n          1251  
-----------------------


In [91]:
a = st.test_equal_odds()
print(a)

pvalue      0.3230662837514884
statistic   2.2597955279197053


In [11]:
df = sm.datasets.get_rdataset("Arthritis", "vcd").data

df.fillna({"Improved":"None"}, inplace=True)

tab = pandas.crosstab(df['Treatment'], df['Improved'])
tab = tab.loc[:, ["None", "Some", "Marked"]]
tab
# table = sm.stats.Table(tab)
# print(table)

Improved   None  Some  Marked
Treatment                    
Placebo      29     7       7
Treated      13     7      21

In [55]:
data.data

smoking_yes_cancer_yes  smoking_yes_cancer_no  \
Location                                                   
Beijing                       126                    100   
Shanghai                      908                    688   
Shenyang                      913                    747   
Nanjng                        235                    172   
Harbin                        402                    308   
Zhengzhou                     182                    156   
Taiyuan                        60                     99   
Nanchang                      104                     89   

           smoking_no_cancer_yes  smoking_no_cancer_no  
Location                                                
Beijing                       35                    61  
Shanghai                     497                   807  
Shenyang                     336                   598  
Nanjng                        58                   121  
Harbin                       121                   215  
Zhengzhou                     72                    98  
Taiyuan                       11                    43  
Nanchang                      21                    36

In [71]:
data = sm.datasets.china_smoking.load_pandas()

mat = np.asarray(data.data)

tables = [np.reshape(x.tolist(), (2, 2)) for x in mat]

st = sm.stats.StratifiedTable(tables)

print(st.summary())

                   Estimate   LCB    UCB 
-----------------------------------------
Pooled odds           2.174   1.984 2.383
Pooled log odds       0.777   0.685 0.868
Pooled risk ratio     1.519              
                                         
                 Statistic P-value 
-----------------------------------
Test of OR=1       280.138   0.000 
Test constant OR     5.200   0.636 
                       
-----------------------
Number of tables    8  
Min n             213  
Max n            2900  
Avg n            1052  
Total n          8419  
-----------------------


In [72]:
data.data

smoking_yes_cancer_yes  smoking_yes_cancer_no  \
Location                                                   
Beijing                       126                    100   
Shanghai                      908                    688   
Shenyang                      913                    747   
Nanjng                        235                    172   
Harbin                        402                    308   
Zhengzhou                     182                    156   
Taiyuan                        60                     99   
Nanchang                      104                     89   

           smoking_no_cancer_yes  smoking_no_cancer_no  
Location                                                
Beijing                       35                    61  
Shanghai                     497                   807  
Shenyang                     336                   598  
Nanjng                        58                   121  
Harbin                       121                   215  
Zhengzhou                     72                    98  
Taiyuan                       11                    43  
Nanchang                      21                    36

In [74]:
mat

array([[126, 100,  35,  61],
       [908, 688, 497, 807],
       [913, 747, 336, 598],
       [235, 172,  58, 121],
       [402, 308, 121, 215],
       [182, 156,  72,  98],
       [ 60,  99,  11,  43],
       [104,  89,  21,  36]])

In [75]:
tables

[array([[126, 100],
        [ 35,  61]]),
 array([[908, 688],
        [497, 807]]),
 array([[913, 747],
        [336, 598]]),
 array([[235, 172],
        [ 58, 121]]),
 array([[402, 308],
        [121, 215]]),
 array([[182, 156],
        [ 72,  98]]),
 array([[60, 99],
        [11, 43]]),
 array([[104,  89],
        [ 21,  36]])]